language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git-core build-essential libssl-dev libncurses5-dev unzip gawk python2.7 subversion

git:
  depth: 3

script:
  - cp openwrt.config .config
  - make -j6 || make V=s

